auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 张煜鹏的博客
url: http://sysuzhyupeng.github.io
feed: /atom.xml
author_info: <a href="https://sysuzhyupeng.github.io/">sysuzhyupeng</a>
